package com.finx.domain.enums;

public enum Province {
    ALBERTA,
    BRITISH_COLUMBIA,
    MANITOBA,
    NEW_BRUNSWICK,
    NEWFOUNDLAND_AND_LABRADOR,
    NOVA_SCOTIA,
    ONTARIO,
    PRINCE_EDWARD_ISLAND,
    QUEBEC,
    SASKATCHEWAN,
    NORTHWEST_TERRITORIES,
    NUNAVUT,
    YUKON
}
